apiVersion: batch/v1
kind: Job
metadata:
  name: art-embed-job
  namespace: ksho1003
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        gpu: l4
      containers:
        - name: art-embed
          image: ksho6/art-recommender:v1
          imagePullPolicy: Always
          command: ["python", "src/3_embed.py"]
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
              nvidia.com/gpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4"
              nvidia.com/gpu: "1"
          env:
            - name: DATA_DIR
              value: "/app/data"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: dsw-pvc